spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frameworkgimal?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: framework
    password: framework1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중 편하게 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect는 최신부턴 자동 인식되지만, 명시해도 됨
        # dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

server:
  port: 8080
